機械学習
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #18
Opened 2023-08-12 18:04 UTC by kawanoichi

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点

## 動作テスト

### 実験方法

### 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

### 実験結果

### 添付資料

2023-08-30 08:28 UTC, bizyutyu requested changes
レビュー途中ですが、疑問点だけ。

2023-08-30 08:28 UTC, bizyutyu commented on src/detect_fig.py
> +YOLO_PATH = os.path.join("..", "etrobocon2023-camera-system", "yolo")  # noqa
```suggestion
YOLO_PATH = os.path.join("yolo")  # noqa
```
では、駄目なんですかね？

2023-08-30 14:08 UTC, KakinokiKanta reviewed
いくつか質問してるので、答えてほしいです。
後、yolo以下が取ってきたやつですかね？

送ってるつもりで、送れていませんでした。すみません。

2023-08-30 15:31 UTC, kawanoichi commented on src/detect_fig.py
> +IMAGE_PATH = os.path.join("..", "etrobocon2023-camera-system", "fig_image")  # noqa
すみません。実行場所の問題があったような...なかったような...後ほど確かめます

2023-08-30 15:43 UTC, kawanoichi commented on src/detect_fig.py
> +                 img_path=IMAGE_PATH / 'test_image.png',
あってる

2023-08-30 15:53 UTC, kawanoichi commented on src/detect_fig.py
> +                 iou_thres=0.45,
以下の理由でYOLOのデフォルト値から変えてません
- 鮮明化後画像で重なって検出されるエラーがでてなくて、変えるにしても適切な値がわからない。
- ベストショット画像を選択する際に、複数重なって検出されても問題ない気がする(検出数があまりにも多いと処理時間が長くなるが、2、3個とかは大差ないと思う)

2023-08-30 15:53 UTC, kawanoichi commented on src/detect_fig.py
> +YOLO_PATH = Path(YOLO_PATH)  # noqa
後ほど回答します

2023-08-31 08:44 UTC, miyashita64 requested changes
全部は見れてないけど、とりあえず

2023-08-31 08:44 UTC, miyashita64 commented on .gitignore
> +!tests/testdata/yolo/weight.pt
```suggestion
!tests/testdata/yolo/weight.pt
!tests/testdata/img/*
```
も必要かも

2023-08-31 08:44 UTC, miyashita64 commented on src/detect_fig.py
> +def check_exists(path) -> None:
指定したパスのファイルが見つからない場合に、処理を分けたいこともあると思うから、bool値返した方がいいと思う。

その場合、関数名もtrue/falseがどっちかわかりやすい名前にしてほしい。

例えば
```suggestion
def is_exist(path) -> bool:
```

2023-08-31 08:44 UTC, miyashita64 commented on src/detect_fig.py
> +            img_path: 画像パス
img_path受け取ってなくね

2023-08-31 08:44 UTC, miyashita64 commented on src/detect_fig.py
> +class Detect():
ファイル名と合わせてfigって入れていいと思う。
というか、ファイル名とクラス名を名詞にするなら、FigDetectorとかになるかな。

もし、フィグに限らず物体検出を行うクラスで、学習したパラメータによって検出対象を切り替えれるようにするなら、ファイル名にfigはいらないかな。

2023-08-31 08:44 UTC, miyashita64 commented on src/detect_fig.py
> +        im0 = cv2.imread(self.img_path)  # BGR
コンストラクタのcheck_exists()で、指定されたパスのファイルが存在したことを確認した？から、読めないことは考えないってことだと思うんだけど、
コンストラクタ時点で指定パスのファイルが存在しているかより、ファイル読み込み自体をtryにした方が確実じゃない？

2023-08-31 08:44 UTC, miyashita64 commented on src/detect_fig.py
> +                 label_data=YOLO_PATH / 'label_data.yaml',
もし、フィグ以外の物体検出のことも考えてるなら、ファイル名はフィグ用だとわかる名前がいいと思う。

```suggestion
                 weights=YOLO_PATH / 'fig_learned_weight.pt',
                 label_data=YOLO_PATH / 'fig_label_data.yaml',
```

実際は、figというより、fig_faceなのかな？

2023-08-31 08:44 UTC, miyashita64 commented on src/detect_fig.py
> +        # 画像の読み込み
大量に使うからimって短い名前にしてると思うけど、せめて、なんなのかのコメントが欲しい。

```suggestion
        # 画像の読み込み im:バウンディング処理画像, im0:入力画像
```

2023-08-31 08:44 UTC, miyashita64 commented on src/detect_fig.py
> +        im = np.ascontiguousarray(im)
これはread_image()の範疇を超えてるんじゃない？

2023-09-02 03:04 UTC, kawanoichi commented on src/detect_fig.py
> +YOLO_PATH = os.path.join("..", "etrobocon2023-camera-system", "yolo")  # noqa
すみません。src直下で実行するときと、etrobocon2023-camera-system直下で実行するのとパスが変わってエラーが出る問題があったので対処できるようにしていたつもりでしたが、できていませんでした。新たに書き換えたのでレビューお願いします。

2023-09-02 03:06 UTC, kawanoichi commented on src/detect_fig.py
> +                 img_path=IMAGE_PATH / 'test_image.png',
すみません。インスタンス化の時に渡していたら不便だなと思ったので、関数部分で渡すことにしました。

2023-09-02 03:06 UTC, kawanoichi commented on .gitignore
> +!tests/testdata/yolo/weight.pt
いらないかな

2023-09-02 03:09 UTC, kawanoichi commented on src/detect_fig.py
> +        im0 = cv2.imread(self.img_path)  # BGR
tryよりFalseを返した方がいいような気がしたので、そうなるように変更しました。

2023-09-02 13:34 UTC, kawanoichi commented on src/detect_fig.py
> +IMAGE_PATH = os.path.join("..", "etrobocon2023-camera-system", "fig_image")  # noqa
[回答](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/pull/18#:~:text=%E3%81%99%E3%81%BF%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82src%E7%9B%B4%E4%B8%8B%E3%81%A7%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B%E3%81%A8%E3%81%8D%E3%81%A8%E3%80%81etrobocon2023%2Dcamera%2Dsystem%E7%9B%B4%E4%B8%8B%E3%81%A7%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B%E3%81%AE%E3%81%A8%E3%83%91%E3%82%B9%E3%81%8C%E5%A4%89%E3%82%8F%E3%81%A3%E3%81%A6%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E5%87%BA%E3%82%8B%E5%95%8F%E9%A1%8C%E3%81%8C%E3%81%82%E3%81%A3%E3%81%9F%E3%81%AE%E3%81%A7%E5%AF%BE%E5%87%A6%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%81%A6%E3%81%84%E3%81%9F%E3%81%A4%E3%82%82%E3%82%8A%E3%81%A7%E3%81%97%E3%81%9F%E3%81%8C%E3%80%81%E3%81%A7%E3%81%8D%E3%81%A6%E3%81%84%E3%81%BE%E3%81%9B%E3%82%93%E3%81%A7%E3%81%97%E3%81%9F%E3%80%82%E6%96%B0%E3%81%9F%E3%81%AB%E6%9B%B8%E3%81%8D%E6%8F%9B%E3%81%88%E3%81%9F%E3%81%AE%E3%81%A7%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%81%8A%E9%A1%98%E3%81%84%E3%81%97%E3%81%BE%E3%81%99%E3%80%82)

2023-09-03 04:02 UTC, miyashita64 requested changes
yoloの中身はよくわかってないけどとりあえず。

2023-09-03 06:18 UTC, kawanoichi commented on src/image_processing.py
> +            return resized_img
finalyは何に使うの？
あと、できれば紹介する記事はPython3のものがいいな。

2023-09-03 06:21 UTC, kawanoichi commented on src/detect_objects.py
> +            return False
例えば？

2023-09-03 06:26 UTC, kawanoichi commented on src/detect_objects.py
> +class DetectedObject():
「DetectObject」でいいか？
「s」については複数検出するからつけてみたけどいらないか。
変更します。

2023-09-03 12:40 UTC, miyashita64 commented on src/detect_objects.py
> +            return False
```
return []
```

の方が、

detect_object()を呼び出す側がシンプルになるかなと思った。あと、不必要に返り値がいろんな型になるのは混乱の元なだと思う。

Falseを返す場合、if通すとかになると思うけど、「画像が読み込めなかった場合」と「物体を検出できなかった場合」ってわざわざ区別して分岐する必要あるのかなって。
```
DetectObject do
objects = do.detect_object(img_path)
if object != False: # 画像が読み込めた場合
  for obj in objects:
    # 検出したオブジェクトに対する処理
else: # 画像が読み込めなかった場合
  # 画像が存在しない場合の処理？
```

空のリストを返す場合
```
DetectObject do
objects = do.detect_object(img_path)
for obj in objects: # 空のリストなら処理は回らない
  # 検出したオブジェクトに対する処理
```

まぁ、forにFalse突っ込んだときの挙動はちゃんと知らんけど、たとえ繰り返しが回らなくて、空のリストを返す場合と同じ書き方ができたとしても、型変わるの気持ち悪くない？

2023-09-03 12:45 UTC, miyashita64 commented on src/detect_objects.py
> +class DetectedObject():
ごめん。sの方は確認したかっただけで、複数返ってくることがわかる名前ってのはいいなと思った。わざわざ戻すまではしなくていいけど。

2023-09-03 13:19 UTC, miyashita64 commented on src/image_processing.py
> +            return resized_img
例は失敬。
※今年の開発では多分問題は起きないとは思うんだけど、書き方としてどうなんだろう。って指摘です。

finallyは、確実に実行したい処理を書くとき、例えば、メモリやファイルの解放とかデータベースとの接続切断とか、に書くらしい。

「確実に実行したい処理」を書くから、たとえtryでreturnしてもfinallyが動くのは正しい挙動だと思うんだけど、知らないうちに動いてたとかありそう。

下の見て、
1. sample_function()の中の処理が実行
2. "Finish"が標準出力
3. sample_function()の返り値をreturn
って動くって、頭から抜けそうじゃない？
```
def run():
  try:
    return sample_function()
  except Exception as e:
    print(e)
  finally:
    print("Finish")
```

tryは、想定される例外を捌くものであって、想定されない例外をうやむやにするのは望ましくないから、例外が想定される処理だけを入れようって話もある。
ここでは、画像読み込みと画像への処理は、「画像が読み込めない」って例外が想定されるけど、returnに対する例外は特に思いつかない。

2023-09-04 05:07 UTC, kawanoichi commented on src/detect_objects.py
> +            return False
「呼び出し側の問題かもしれんが、objectsって変数にFalseが入るのも嫌。」←これは納得
だが、それ以外が理由が不満。
上の例は画像が読み込めなかった場合の処理を書いてるけど下の例は空のリスト処理して終了してるけどそれでいいの？
読み込めなかった場合（＝まだ画像が送られてきていない場合）は再び`do.detect_object(img_path)`を実行すべきでは？
普通にif文で画像を読み込めた時と読み込めなかった時の分岐は書くべきだと思う。
あと、個人的に空のリストは実行側を意識しすぎな気がするからやだな。`None`はいかがですか？

2023-09-04 06:40 UTC, kawanoichi commented on src/detect_objects.py
> +            return False
それとも画像が走行体から送られてきたかどうかの確認をべつでするんだっけ？

2023-09-04 06:51 UTC, kawanoichi commented on src/image_processing.py
> +            return resized_img
前半の意見はただ単にfinallyの使い方が分かってないだけでは？笑
後半の意見には納得しました。書き直します。

2023-09-04 12:45 UTC, miyashita64 commented on src/detect_objects.py
> +            return False
受信したかの確認を物体検出クラスがするのは違う気がするから、別でいいと思う。

2023-09-04 15:49 UTC, KakinokiKanta reviewed
問題なさそうなんですけど、眠すぎて正常な判断ができてるか心配なので、明日の朝もう一回見てからLGTM出そうと思います。すみません。

2023-09-04 17:21 UTC, miyashita64 commented
lgtm
![LGTM](https://image.lgtmoon.dev/73911)

2023-09-05 03:43 UTC, aridome222 approved these changes
レビュー遅くなりました。問題ないと思われます。
![LGTM](https://image.lgtmoon.dev/134760)

2023-09-05 03:58 UTC, KakinokiKanta approved these changes
ありがとうございます!!
![LGTM](https://image.lgtmoon.dev/188940)

2023-09-05 05:06 UTC, miyashita64 approved these changes

2023-09-05 06:36 UTC, bizyutyu approved these changes
お疲れ様です。
![LGTM](https://image.lgtmoon.dev/112948)

2023-09-05 07:04 UTC, miyashita64 approved these changes

2023-09-05 08:32 UTC, kodama0720 approved these changes
![lgtm3](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/assets/83354922/e59add8e-5678-4779-b8e6-cfee4916761d)

2023-09-08 11:59 UTC, merged