fix: 試走会を踏まえての修正
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #23
Opened 2023-09-02 12:13 UTC by miyashita64

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- 競技システムへのリクエストを修正
- 通信の処理をtry内で行うように変更

## 動作テスト

### 実験方法
試走会にてIoT列車のPWM値を設定できることを確認できた。

2023-09-03 05:41 UTC, kodama0720 approved these changes
良いと思います。
一点だけ質問

2023-09-03 05:41 UTC, kodama0720 commented on src/camera_interface.py
> +        self.camera = cv2.VideoCapture(camera_id, cv2.CAP_DSHOW)
CAP_DSHOWって何に必要なの？

2023-09-03 07:23 UTC, kawanoichi requested changes
物体検出のタスクでresize_img()は消すので意味ないかもしれないが、念のためコメント
以下の文いらない
```
height, width, _ = img.shape
```

2023-09-03 07:23 UTC, kawanoichi commented on src/official_interface.py
> +        except:
エラーメッセージは表示させないの？
あと、このreturnの書き方はfinallyを気にしているのかな？ここか[物体検出](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/pull/18#:~:text=try%E5%86%85%E3%81%A7%E3%81%AF%E3%81%82%E3%82%93%E3%81%BE%E3%82%8Areturn%E3%81%97%E3%81%AA%E3%81%84%E6%96%B9%E3%81%8C%E3%81%84%E3%81%84%E3%81%A8%E6%80%9D%E3%81%86%E3%80%82)で解説お願いします。

2023-09-03 07:23 UTC, kawanoichi commented on src/official_interface.py
> +            # 指定された画像をリクエストに含める
「リクエストに含める」という文を理解できていないかもしれないが、ここでは画像を読み取っているだけでは？
送信するデータを準備することは「リクエストに含める」って言うの？

2023-09-03 13:29 UTC, miyashita64 commented on src/official_interface.py
> +        except:
物体検出側に書いたけど、こっちにも無駄な処理がtryに入ってるので修正します。

2023-09-03 13:44 UTC, miyashita64 commented on src/camera_interface.py
> +        self.camera = cv2.VideoCapture(camera_id, cv2.CAP_DSHOW)
開発環境ではなくても動いてたんだけど、試走会のカメラだと、これがないと動かなかった。
CAP_DSHOWを指定すると、Direct Show経由で映像を扱うようになるらしい。

> DirectshowはMicrosoftが提供しているビデオ（マルチメディア）を扱う際の様々なコンポーネントの集合体です。プログラムの要求に応じてビデオの加工、再生、録画、フォーマット変換などの処理を行うことができます。
> 
> Directshow経由でカメラの画像を読み込むことにより、以下のようなメリットがあります。
> 
> - カメラの設定を簡単に変更できる"CAP_PROP_SETTING"が使用できる。
> →[簡単にカメラの設定変更用ウィンドウを出す方法](https://www.klv.co.jp/corner/python-opencv-camera-setting-window.html)
> - OpenCVで発生する、解像度の設定（FRAME _WIDTH、FRAME_HEIGHT）が正しく認識されない問題を回避できる。

だそうです。

参考　https://www.klv.co.jp/corner/python-opencv-video-capture.html

2023-09-03 13:46 UTC, miyashita64 commented on src/official_interface.py
> +            # 指定された画像をリクエストに含める
言わないね

2023-09-04 08:32 UTC, kawanoichi requested changes
変更or回答おねがいします

2023-09-04 08:32 UTC, kawanoichi commented on src/official_interface.py
> +    def __init__(self, message):
```suggestion
    def __init__(self, message: str):
```
引数のところに型指定がないです。他のところもお願いします

2023-09-04 08:32 UTC, kawanoichi commented on src/official_interface.py
>          return success
これ例外起きたときにsuccessは定義されてないことになるんじゃないけ？
たぶんreturnでエラーでる？

2023-09-04 08:32 UTC, kawanoichi commented on src/official_interface.py
>          return success
ここも

2023-09-04 08:32 UTC, kawanoichi commented on src/official_interface.py
> +            response = requests.put(url)
これ分かることなのかわからないが、これって通信失敗の場合って必ず何かしらの数値が返ってくるの？ずっと接続待ち状態になるってことはない？
必ず数値帰ってくるならtestの方で通信失敗時の処理も書くべきでは？

2023-09-04 08:38 UTC, kawanoichi commented on src/official_interface.py
> +        except:
64行目
```
　　 headers = {
            "Content-Type": "image/png"
        }
        # チームIDをリクエストに含める
        params = {
            "id": cls.TEAM_ID
        }
```
ここのコメントも。
あと、headers と paramsでコメントを書くのか書かないのかの統一をお願いします。

2023-09-04 08:43 UTC, kawanoichi requested changes

2023-09-04 08:43 UTC, kawanoichi commented on src/official_interface.py
>          }
ここのコメントも。
あと、headers と paramsでコメントを書くのか書かないのかの統一をお願いします。

2023-09-04 08:43 UTC, kawanoichi commented on src/camera_interface.py
> +        self.camera = cv2.VideoCapture(camera_id, cv2.CAP_DSHOW)
児玉君の質問への回答をコメントとして記述するべきだと思います。
URL貼るでもいいし

2023-09-04 11:22 UTC, miyashita64 commented on src/official_interface.py
>          return success
tryの外で定義してる

2023-09-04 11:25 UTC, miyashita64 commented on src/official_interface.py
> +            response = requests.put(url)
サーバに届いていれば、何かしらのステータスコードは返ってくるはず。
接続待ちは一定時間でタイムアウトするはず。

2023-09-04 15:58 UTC, KakinokiKanta reviewed
処理に問題はないと思います。1か所質問してるので、回答してもらえたら

2023-09-04 15:58 UTC, KakinokiKanta commented on src/official_interface.py
> +            response = requests.put(url)
これってタイムアウトした場合は、ステータスコードってどうなるんですか?

2023-09-04 16:01 UTC, KakinokiKanta approved these changes

2023-09-04 16:01 UTC, kawanoichi requested changes
すみません。前回の範囲ですが、
```
        self.video = cv2.VideoWriter(
            f"{self.output_dir}{now}.mp4", codec, 20.0, (640, 480))
```
ここの(640, 480)のサイズは指定するべきですか？これ送る画像の指定サイズだよね？

2023-09-04 16:07 UTC, miyashita64 commented
これは、IoT列車の検出できればいいから、そこそこ早くて、精度的に(少なくとも今の所は)問題もないから、この解像度でいいかなと思う。

2023-09-04 17:10 UTC, kawanoichi approved these changes
![185745](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/assets/96767490/69ba33ff-dd3d-4614-8f88-20e005782d34)

2023-09-05 03:22 UTC, aridome222 approved these changes
レビュー遅れました。見た感じ大丈夫そうです。
![LGTM](https://image.lgtmoon.dev/139294)

2023-09-05 04:22 UTC, merged