close #24 走行体からカメラシステムへ画像を送信する
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #25
Opened 2023-09-05 11:49 UTC by desty505

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- send_fig.shを追加しました

## 動作テスト
- bashファイルでのテストはまだ行ってません

2023-09-07 02:54 UTC, miyashita64 requested changes
1点だけ対応お願いします。

2023-09-07 02:54 UTC, miyashita64 commented on send_fig.sh
> +REMOTE_DIRECTORY="./fig_image/"
```suggestion
# リモート上のコピー元のパス
REMOTE_DIRECTORY="~/work/RasPike/sdk/workspace/etrobocon2023/rear_camera_py/image_data/"
```
かな。

`LOCAL_DIRECTORY="./fig_image/"`
もどこかに追加していいかも

2023-09-07 07:13 UTC, bizyutyu commented on send_fig.sh
> +# 第1引数が接続先IPアドレス、第2引数が送信する画像ファイル名
```suggestion
# 第1引数が接続先IPアドレス、第2引数が送信元画像ファイル名
```
上手い言葉が見つからないけど、"送信する"は、少し違う気がする。もっと良い言い方が有るかも、、

2023-09-07 07:13 UTC, bizyutyu commented on send_fig.sh
> +# 送信する画像ファイル
```suggestion
# 送信元画像ファイル
```
ここも

2023-09-07 08:04 UTC, KakinokiKanta approved these changes
他の人の変更に対応してくれたら、問題ないです！お疲れ様です！
![LGTM](https://image.lgtmoon.dev/221533)

2023-09-07 12:25 UTC, bizyutyu approved these changes
LGTM！お疲れ様です。
![LGTM](https://image.lgtmoon.dev/201033)

2023-09-08 06:01 UTC, miyashita64 approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/142904)

2023-09-08 06:03 UTC, miyashita64 commented
lgtm出した後でなんだけど、「送信」とか「転送」を全部「コピー」に統一すれば、@bizyutyuの指摘は解消できるかな？

2023-09-08 06:36 UTC, kawanoichi commented
このbashファイルはカメラシステムが実行するんやろうけど実行するタイミングって何を想定してる？

2023-09-08 08:03 UTC, bizyutyu commented
> lgtm出した後でなんだけど、「送信」とか「転送」を全部「コピー」に統一すれば、@bizyutyuの指摘は解消できるかな？

確かに「コピー」の方が良い気がします！

2023-09-08 12:45 UTC, desty505 commented
> このbashファイルはカメラシステムが実行するんやろうけど実行するタイミングって何を想定してる？

カメラシステム側で画像を必要とした際に呼び出すことを想定しています。

2023-09-08 13:33 UTC, kawanoichi requested changes
ファイル名がsendだとカメラシステムから走行体に送っている感じがするのでファイル名を変えてほしいです。
`copy_image.sh`もしくは`receive_image`など...

2023-09-08 13:38 UTC, kawanoichi approved these changes
LGTM！

2023-09-10 08:33 UTC, merged