ロボコンスナップ攻略クラスの作成
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #27
Opened 2023-09-10 21:24 UTC by kawanoichi

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点

## 動作テスト

### 実験方法

### 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

### 実験結果

### 添付資料

2023-09-16 14:33 UTC, aridome222 commented on src/robo_snap.py
> +                0: "Fig", 1: "FrontalFace", 2: "Profile"
```suggestion
            検出項目:
                0: "Fig", 1: "FrontalFace", 2: "Profile"

```

上記の説明が欲しいです。Profileは横顔という意味ですか？

2023-09-16 14:45 UTC, aridome222 commented on src/robo_snap.py
> +            except Exception as e:
ここで、エラー文をprintせず省略しているのはなぜですか？

2023-09-17 09:55 UTC, miyashita64 requested changes
勘違いしてるとこあったらごめん

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +    def exist_image(self) -> str:
```suggestion
    def exist_image(self) -> (str, str):
```

かな？

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +            img_name     (str): 画像ファイル名
インデント

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +            # # リサイズ
```suggestion
            # リサイズ
```

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +                pre_score = score
どちらかといば、candidate_scoreじゃね？
もしくは、max_scoreとか？

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +                self.candidate_img_path = processed_img_path
これ、メンバで持つ必要あるっけ？

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +        if sent_to_official is False:
```suggestion
        # 全ての画像が閾値を越えなかった場合
        if sent_to_official is False:
```
とか欲しい

2023-09-17 09:55 UTC, miyashita64 commented on yolo/utils/torch_utils.py
> +    #     x.requires_grad = True
この辺りのコメントアウトはそのままでいいの？

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +                    #     and (y2_min < y1_max and y1_min < y2_max)
消し忘れ

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +        index_of_label_2 = np.where(objects_np[:, 5] == 2)
```suggestion
        index_of_fig = np.where(objects_np[:, 5] == 0) # フィグ全身
        index_of_front = np.where(objects_np[:, 5] == 1) # 正面
        index_of_profile = np.where(objects_np[:, 5] == 2) # 横顔
```

とかの方がわかりやすいかな

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +                for j in objects_np[index_of_label_1]:
```suggestion
            for fig_obj in objects_np[index_of_fig]:
                for front_obj in objects_np[index_of_front]:
```
とか？
できるだけ、意味ある名前をつけて欲しい

2023-09-17 09:55 UTC, miyashita64 commented on src/robo_snap.py
> +            if score == 5:
```suggestion
            # スコアが最大の場合
            if score == 5:
```

2023-09-17 12:20 UTC, kawanoichi commented on yolo/utils/torch_utils.py
> +    #     x.requires_grad = True
うん

2023-09-17 12:32 UTC, kawanoichi commented on src/robo_snap.py
> +        index_of_label_2 = np.where(objects_np[:, 5] == 2)
え、NOTEの説明だけじゃ不満？

2023-09-17 12:37 UTC, kawanoichi commented on src/robo_snap.py
> +                    #     and (y2_min < y1_max and y1_min < y2_max)
コメントのつもり

2023-09-17 15:49 UTC, miyashita64 commented on src/robo_snap.py
> +        index_of_label_2 = np.where(objects_np[:, 5] == 2)
下の処理で、label_1とか出て来た時になんのことかわかりにくいと思う。
コメントはなくてもいいけど

2023-09-17 15:57 UTC, miyashita64 commented on src/robo_snap.py
> +                    #     and (y2_min < y1_max and y1_min < y2_max)
なるほど。失礼。

2023-09-18 01:37 UTC, aridome222 approved these changes
修正お疲れ様です。
![LGTM](https://image.lgtmoon.dev/201771)

2023-09-18 03:18 UTC, bizyutyu requested changes
レビュー遅くなりました。
今回の変更分ではないですが、camera_systemの30行目以降あたりの部分についてです。
`````            elif state == "lap":
                tt = TrainTracker(0)
                # Webカメラのキャリブレーション
                tt.calibrate()
                # IoT列車の監視を開始
                tt.observe()
`````  
Lapゲート通過しないとWebカメラキャリブレーションができなくなっているので、できれば修正お願いします。

2023-09-18 03:28 UTC, bizyutyu commented
不要かもしれませんが、修正例です。 間違っていたらすいません。  
   ```
  while True:
           # Webカメラのキャリブレーション
           calibrate_flag = true;
　　　if calibrate_flag == true:
                tt = TrainTracker(0)
                tt.calibrate()
                calibrate_flag = false:
            state = client.get_robot_state()
            # 走行体の状態が"finish"になった時、終了する。
            if state == "finish":
                print(state)
                break
            elif state == "lap":
                # IoT列車の監視を開始
                tt.observe()
            else:
                print(state)
            # 2秒待つ
            time.sleep(2)

        # ロボコンスナップ攻略開始
        snap = RoboSnap(self.raspike_ip)
        snap.start_snap()
```

2023-09-18 08:44 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/221800)

2023-09-18 09:27 UTC, bizyutyu approved these changes
お疲れ様です。LGTM！
![LGTM](https://image.lgtmoon.dev/222524)

2023-09-18 17:24 UTC, KakinokiKanta approved these changes
遅くなって申し訳ないです。
![LGTM](https://image.lgtmoon.dev/222540)

2023-09-18 18:02 UTC, miyashita64 approved these changes
お疲れ様です。
![LGTM](https://image.lgtmoon.dev/169962)

2023-09-18 18:06 UTC, merged