close #28 撮影終了フラグを立てる関数を追加
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #29
Opened 2023-09-17 10:53 UTC by miyashita64

## チェックリスト

- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
Clientクラスに走行体の撮影終了フラグを立てる関数を追加
テストを追加

## 動作テスト
明日中に[close #113 撮影終了フラグを管理する ](https://github.com/KatLab-MiyazakiUniv/etrobocon2023/pull/117)と合わせて実機で検証します。

2023-09-17 13:50 UTC, kawanoichi requested changes
authorに名前記述するの忘れているのでそちらもよろしくお願いします。

2023-09-17 13:50 UTC, kawanoichi commented on src/client.py
> +        url = f"http://{self.server_ip}/"
```suggestion
        url = f"http://{self.server_ip}/robot_info/skip_camera_action_true"
```
理解できていなかったらごめん。走行体側でこのURLって言ってた気がするんだけど、それでいいんだっけ？

2023-09-17 16:20 UTC, miyashita64 commented on src/client.py
> +        url = f"http://{self.server_ip}/"
よくないです

2023-09-17 18:49 UTC, kawanoichi requested changes

2023-09-17 18:49 UTC, kawanoichi commented on tests/test_client.py
> +        client.set_true_camera_action_skip()
前の担当の人の時にも聞くべきやったかもやけど。
このテストって何を確かめることができてるん？最初はうまく実行できるかの確認やと思ってたけどtry文だから何が起こってもこのテストはうまくいく？
せめて以下を実行すべき？
```
# 13行目
assert client.get_robot_state() == None

# 19行目
assert client.set_true_camera_action_skip() == False
```

2023-09-18 06:28 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/35592)

2023-09-18 12:24 UTC, KakinokiKanta reviewed
コメントで残しているところの対応をお願いします。

2023-09-18 12:24 UTC, KakinokiKanta commented on src/camera_system.py
> +        server_ip = "172.20.1.1:8000"
etrobo2023の方でもコメントしたんですが、Bluetooth接続がうまくいかなくてWiFI接続することになった場合に変更しなければいけない部分をwikiなどにまとめておいてもらえると助かります。

2023-09-18 17:46 UTC, aridome222 approved these changes
見たところ、大丈夫そうです。お疲れ様です。
![LGTM](https://image.lgtmoon.dev/134789)

2023-09-18 18:05 UTC, miyashita64 commented on src/camera_system.py
> +        server_ip = "172.20.1.1:8000"
Wi-FiやBluetoothとの接続確認等のコマンドも含めて今週中にまとめときます

2023-09-18 18:12 UTC, kawanoichi approved these changes
![188950](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/assets/96767490/ba1670ac-7e97-4e29-8fd4-a65f5a0964f0)

2023-09-19 03:48 UTC, bizyutyu approved these changes
LGTM！
![LGTM](https://image.lgtmoon.dev/219776)

2023-09-19 17:27 UTC, KakinokiKanta approved these changes
ドキュメントにまとめるのよろしくお願いします。
LGTM!

2023-09-19 17:28 UTC, merged