close #32 動作確認用の競技システムの構築とそれに伴う修正
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #33
Opened 2023-09-23 13:28 UTC by miyashita64

## チェックリスト
- [x] format(autopep8) している
- [x] コーディング規約(pep8)に準じている
- [x] チケットの完了条件を満たしている

## 変更点
- フィグ画像の送信成功のステータスコードの修正(200だと思ってたら201でした)
- 動作確認用競技システムの起動・停止を行うスクリプトを追加

以下、今後の動作確認のために競技システムをいじりました。
- 実際のIoT列車にPWM値を指定する関数setPWM()の呼び出しをコメント化(Server Errorになるため)
- 各APIのレスポンスに以下の情報を追加(カメラシステムはステータスコードしか参照しないため影響はないはず)
  - IoT列車のPWM値指定API:  pwm: setPWM()の引数に入る値
  - フィグ画像の送信API: path: 送信したフィグ画像が保存されたパス

## 動作テスト
研究室PCのカメラシステムと競技システムをLANケーブルで接続し、OfficialInterfaceを実行し、以下を確認した。
- IoT列車のPWM値指定については、競技システムが正しく値を受け取っていること
フィグ画像の送信では、競技システムが指定しいるパスに送信した画像が保存されていること
- それぞれ成功のステータスコードを返すこと

2023-09-25 08:26 UTC, kawanoichi requested changes
bashファイルの中の処理自体が正しいかどうかはわかりません。
起動しているならいいと思います。

2023-09-25 08:26 UTC, kawanoichi commented on src/official_interface.py
> +    ("test-start")
この書き方を知らない。
コメント？

2023-09-25 08:26 UTC, kawanoichi commented on src/official_interface.py
> +    OfficialInterface.upload_snap("../fig_image/fig1.png")
いつでもtestできるようにするならば、testdatasの画像を使用すればいいんじゃない？
今fig_imageの中には何も画像はないから取得するところから始めないといけなくなる

2023-09-25 08:26 UTC, kawanoichi commented on scripts/run_official_server.sh
> +SERVE_COMMAND="cd /opt/compesys && sudo npm run start"
`serve`は供給する的な意味？
それとも`server`？

2023-09-25 08:36 UTC, miyashita64 commented on scripts/run_official_server.sh
> +SERVE_COMMAND="cd /opt/compesys && sudo npm run start"
「提供する」みたいな意味で書いてる。
SERVE_START_COMMANDぐらい書いた方がいい？

2023-09-25 09:08 UTC, kawanoichi commented on scripts/run_official_server.sh
> +SERVE_COMMAND="cd /opt/compesys && sudo npm run start"
そうだねserve_commandじゃわかりにくいかも
そしてserveよりprovideの方がいいかな

2023-09-25 09:45 UTC, miyashita64 commented on scripts/run_official_server.sh
> +SERVE_COMMAND="cd /opt/compesys && sudo npm run start"
ファイル名に合わせて
RUN_SERVER_COMMAND
にしました

2023-09-25 10:40 UTC, kawanoichi approved these changes
![13500](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/assets/96767490/7a22b512-9d38-4c73-8b0e-2d92db3e1466)

2023-09-26 04:57 UTC, KakinokiKanta approved these changes
LGTM!!
![LGTM](https://image.lgtmoon.dev/77150)

2023-09-26 05:04 UTC, desty505 approved these changes
LGTM！

2023-09-26 05:29 UTC, bizyutyu approved these changes
お疲れ様です。
![LGTM](https://image.lgtmoon.dev/18940)

2023-09-26 05:30 UTC, merged