# ticket-34 試走前の調整と処理の修正
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #35
Opened 2023-09-26 15:45 UTC by kawanoichi

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点

## 動作テスト

2023-10-07 07:54 UTC, kodama0720 requested changes

2023-10-07 07:54 UTC, kodama0720 commented on src/robo_snap.py
>          """
img_pathも返す？

2023-10-07 15:25 UTC, miyashita64 requested changes
変数名ぐらい

2023-10-07 21:20 UTC, aridome222 requested changes
疑問に思った所があったので、回答お願いします。

2023-10-07 21:24 UTC, aridome222 commented on src/robo_snap.py
> -        return None, None
for文の中でreturnされずにfor文を抜けた場合に`return None, None`って必要ないんでしょうか？

2023-10-07 21:39 UTC, aridome222 requested changes

2023-10-07 21:39 UTC, aridome222 commented on src/robo_snap.py
> -        return None, None
for文の中でreturnされずにfor文を抜けた場合にreturn None, Noneって必要ないんでしょうか？

2023-10-07 21:39 UTC, aridome222 commented on src/robo_snap.py
> +                    self.successful_send_fig_B = True
候補画像をアップロードしていない状態で、ベストショット画像撮れたけど、アップロードできなかったという可能性は無いですかね？
候補画像に関しては分かるんですけど、figB画像とベストショット画像って撮れたら即アップロードするので、
figB画像やるならベストショット画像に対しても送信試みした方が良いと思いました。

2023-10-08 08:47 UTC, kawanoichi commented on src/camera_system.py
> +PROJECT_DIR_PATH = os.path.dirname(script_dir)
ちなみに理由は？

2023-10-08 08:55 UTC, kawanoichi commented on src/robo_snap.py
> +                    self.successful_send_fig_B = True
確かに！！！

2023-10-08 09:05 UTC, kawanoichi commented on src/robo_snap.py
> -        return None, None
for文を抜けるパターンがあるっけ？

2023-10-08 09:45 UTC, miyashita64 commented on src/camera_system.py
> +PROJECT_DIR_PATH = os.path.dirname(script_dir)
グローバルにしてると、このファイルをimportしたファイルからscript_dirにアクセスできるようになるけど
①他のファイルで同じ名前の変数を使おうとしたときに混乱が起きる恐れがある。importした側でscript_dirの中身とかいじった場合、camera_systemの動きに影響を与えるかもしれない。
②他のクラスからもこの変数を共有したいならグローバル変数でもいいけど、その場合その変数を使うためにcamera_systemをimportするよりも、共有の値用のファイルを作るべきだと思う(cppのSystemInfo的なやつ)

2023-10-08 09:48 UTC, aridome222 commented on src/robo_snap.py
> -        return None, None
受信できなかったときcontinueしてますが、for img_name in self.img_list:で、どの画像に対しても受信できなかった場合にfor文を抜ける（終える）パターンがあると思ったのですが、そんなことは無いですかね？

2023-10-08 10:32 UTC, kawanoichi commented on src/camera_system.py
> +PROJECT_DIR_PATH = os.path.dirname(script_dir)
`import PROJECT_DIR_PATH` もしくは `import *` してるファイルがあるならだけど、してないならいいんじゃね？

2023-10-08 10:38 UTC, aridome222 requested changes

2023-10-08 10:38 UTC, aridome222 commented on src/robo_snap.py
> +        self.best_shot_img_path = None
220行目あたりの
```
# ベストショット確定だと判断した場合
                if score == 5:
                    self.best_shot_img = img_name
                    # 候補画像のアップロード
                    if OfficialInterface.upload_snap(img_path):
```
を
```
# ベストショット確定だと判断した場合
                if score == 5:
                    self.best_shot_img = img_name
                    self.best_shot_img_path = img_path
                    # 候補画像のアップロード
                    if OfficialInterface.upload_snap(self.best_shot_img_path):
```
にしないとself.best_shot_img_pathはずっとNoneのままになってしまいますね。

2023-10-08 10:54 UTC, kawanoichi commented on src/robo_snap.py
> -        return None, None
たしかに。ありがとう！！バグです

2023-10-08 10:58 UTC, kawanoichi commented on src/robo_snap.py
> +        self.best_shot_img_path = None
度々ありがとう

2023-10-08 12:35 UTC, aridome222 approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/224225)

2023-10-08 12:40 UTC, miyashita64 commented
お疲れ様です
![LGTM](https://image.lgtmoon.dev/202647)

2023-10-08 13:16 UTC, miyashita64 approved these changes

2023-10-08 13:51 UTC, bizyutyu approved these changes
大丈夫だと思います。お疲れ様です。
![LGTM](https://image.lgtmoon.dev/157526)

2023-10-08 20:30 UTC, kodama0720 approved these changes
![LGTM](https://image.lgtmoon.dev/121279)

2023-10-09 08:39 UTC, merged