close #38 キャリブレーション時にカメラIDを指定する
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #39
Opened 2023-10-09 17:18 UTC by miyashita64

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
- キャリブレーション中のIoT列車の監視範囲指定の際にカメラIDを指定する処理を追加
- 監視時にカメラの映像を確認できないバグを修正(スリープを追加)

## 動作テスト
- キャリブレーションでカメラIDを設定できることを確認した(動画参照)。
- 指定範囲内を動体が通過した際に、競技システムへリクエストを送ろうとすることを確認した。

キャリブレーションの様子(printについては少し変えてます)

2023-10-18 10:27 UTC, kawanoichi commented on src/train_tracker.py
> +        self.camera = None
いらない

2023-10-18 11:04 UTC, kawanoichi requested changes
今回の内容ではないですが、train_tracker.pyのdetect_train()のArgsでinitial_frameの説明がないです。

2023-10-18 11:04 UTC, kawanoichi commented on src/camera_system.py
> -                # TODO:observeが"q"を押さないと終了しないバグを修正
今回の範囲ではないんだが、以下の修正の検討よろしく。
スナップ始まるときの条件式に`state != pre_state`があるけど、これ何のためにあるのかよくわかってない

変更前
```
        while True:
            state = client.get_robot_state()
            # 走行体の状態が"finish"になった時、終了する。
            if state == "finish":
                print(state)
                break
            elif state == "lap" and state != pre_state:
                # IoT列車の監視を開始
                tt.observe()

                # ロボコンスナップ攻略開始
                snap = RoboSnap(self.raspike_ip)
                snap.start_snap()
            else:
                print(state)

            # 状態の保持
            pre_state = state
            # 2秒待つ
            time.sleep(2)
```
変更後
```
        while True:
            state = client.get_robot_state()
            # 走行体の状態が"finish"になった時、終了する。
            if state == "finish":
                print(state)
                break
            elif state == "lap":
                # IoT列車の監視を開始
                tt.observe()

                # ロボコンスナップ攻略開始
                snap = RoboSnap(self.raspike_ip)
                snap.start_snap()
                break
            else:
                print(state)

            # 2秒待つ
            time.sleep(2)
```

2023-10-18 13:54 UTC, kodama0720 approved these changes
見た感じ良いと思います。
強いて言うならrキーとqキー忘れそう（使う人が分かるならいいです）

2023-10-18 15:13 UTC, miyashita64 commented on src/train_tracker.py
> +        cv2.namedWindow(WINDOW_NAME)
IoT列車攻略中に画面上に映像と監視範囲を表示するウィンドウ。攻略自体には必要ないけど、動作確認用で常に動かしててもいいかと思ってる。

2023-10-18 15:15 UTC, miyashita64 commented on src/train_tracker.py
> +                key = cv2.waitKey(1)
無限ループで1msの入力時間が来続ける形だから多分問題ないと思う。少なくとも実像中は一回もキー入力は無視されなかった

2023-10-19 10:24 UTC, kawanoichi requested changes

2023-10-19 10:49 UTC, kawanoichi approved these changes
![104534](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/assets/96767490/f701ea65-b617-47cf-9ec2-4a5dc5730b53)

2023-10-19 15:39 UTC, bizyutyu reviewed
特に問題はないように思います。お疲れ様です。
![LGTM](https://image.lgtmoon.dev/34183)

2023-10-19 15:40 UTC, bizyutyu approved these changes

2023-10-19 15:44 UTC, bizyutyu commented on src/camera_system.py
> -                # TODO:observeが"q"を押さないと終了しないバグを修正
すでに解決していると思うので確認になるのですが、`state != pre_state:``がないと、ゴールまでにロボコンスナップ攻略が終わった場合に、もう一度IoT攻略が始まるという認識で合ってますかね？

2023-10-20 06:56 UTC, desty505 approved these changes
LGTM

2023-10-20 09:18 UTC, merged