close #コースアウト時に画像を送信できるように変更
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #43
Opened 2023-11-03 10:36 UTC by aridome222

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点

## 動作テスト

### 実験方法

### 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

### 実験結果

### 添付資料

2023-11-09 01:14 UTC, miyashita64 requested changes
いくつか対応お願いします

2023-11-09 01:14 UTC, miyashita64 commented on src/robo_snap.py
> +                    elif start_time != 0.0:
```suggestion
                    elif i != 0:
```
最初のループって意味ならiを使うべきだと思う。

2023-11-09 05:25 UTC, kawanoichi requested changes
前回のミーティングでfinallyで行うのは卑怯ということで、今回のタスクを行うことになったはずなので、finallyでの送信はすべきではないと思います。
以下の変更への検討をお願いします。
- finally -> exceptに変更
- `if timeout_flag:`部分で候補写真の送信を行う.

あと、写真間の待機時間をそれぞれで保持している理由はありますか？個人的に全部同じ時間でいいのではないかと思うのですが、別々に設定したほうがいい理由があったら回答お願いします。

2023-11-09 05:57 UTC, aridome222 commented on src/robo_snap.py
> +                            break
外のtryにある最後のfinalyで送信してるつもりです。
この修正で、raiseした後ってfinalyに行きますか？
行かない場合はraiseした後にbreakが必要ですよね？

2023-11-09 06:10 UTC, aridome222 commented on src/robo_snap.py
> +                            break
raiseで直接finally行きますね。2回breakしてfinallyに行こうとしてました。
では、下記のコードを消しておきます。
```
# タイムアウトフラグがTrueなら、ループを抜けてfinallyで現時点でのベスト画像を送信する
if timeout_flag:
    break
```

2023-11-09 06:51 UTC, aridome222 commented
> 前回のミーティングでfinallyで送信を行うのは卑怯ということで、今回のタスクを行うことになったはずなので、finallyでの送信はすべきではないと思います。 以下の変更への検討をお願いします。
> 
> * finally -> exceptに変更
> * `if timeout_flag:`部分で候補写真の送信を行う.

変更承知しました。

> あと、写真間の待機時間をそれぞれで保持している理由はありますか？個人的に全部同じ時間でいいのではないかと思うのですが、別々に設定したほうがいい理由があったら回答お願いします。

単純に各区間における写真間の待機時間は異なるからと言うのもあるのですが、固定した場合を考えると、
もし例えば、どの区間においても待機時間を15秒に固定して、区間1で画像を取得するまで10秒、区間2で5秒かかるとした場合、区間1でコースアウトしたと判定するまでに少なくとも5秒以上、区間2の場合は少なくとも10秒以上かかります。この判定時間が長いほど、コースアウトしてから場外に出てしまったり、相手コースの方に侵入してしまった場合に、画像を送信できない可能性が高まるので、個別に保持した方が良いと思っています。
でも、よく考えたら、どの区間も同じくらいの待機時間なので、同じ時間でもいいのかなと思いました。

2023-11-09 07:30 UTC, kawanoichi commented
> > 前回のミーティングでfinallyで送信を行うのは卑怯ということで、今回のタスクを行うことになったはずなので、finallyでの送信はすべきではないと思います。 以下の変更への検討をお願いします。
> > 
> > * finally -> exceptに変更
> > * `if timeout_flag:`部分で候補写真の送信を行う.
> 
> 変更承知しました。 `if timeout_flag:`部分で候補写真の送信を行う.の部分って、raiseすれば直接exceptに行って送信するではだめなんでしょうか？
> 
> > あと、写真間の待機時間をそれぞれで保持している理由はありますか？個人的に全部同じ時間でいいのではないかと思うのですが、別々に設定したほうがいい理由があったら回答お願いします。
> 
> 単純に各区間における写真間の待機時間は異なるからと言うのもあるのですが、固定した場合を考えると、 もし例えば、どの区間においても待機時間を15秒に固定して、区間1で画像を取得するまで10秒、区間2で5秒かかるとした場合、区間1でコースアウトしたと判定するまでに少なくとも5秒以上、区間2の場合は少なくとも10秒以上かかります。この判定時間が長いほど、コースアウトしてから場外に出てしまったり、相手コースの方に侵入してしまった場合に、画像を送信できない可能性が高まるので、個別に保持した方が良いと思っています。 でも、よく考えたら、どの区間も同じくらいの待機時間なので、同じ時間でもいいのかなと思いました。

raiseで終了したら、処理が終了してしまうよね。可能性として低いのだが、例えばBの画像を受信する前にタイムオーバーしてraiseによる送信をしたらBはあきらめることになるよね。タイムオーバーはあくまでタイムアウトの推測であって絶対ではないので処理は続けていいと思う。

時間については検証を行うのであれば的確な時間を検証してもいいけど、あまり時間ないよね。仮に別々にしたいってなっても制限時間を配列として保持するか、一つの値として保持するかの違いで済むから分けたいと思ったときに複数設定するように変更すればいいと思う

2023-11-09 13:14 UTC, kawanoichi commented
> > > > 前回のミーティングでfinallyで送信を行うのは卑怯ということで、今回のタスクを行うことになったはずなので、finallyでの送信はすべきではないと思います。 以下の変更への検討をお願いします。
> > > > 
> > > > * finally -> exceptに変更
> > > > * `if timeout_flag:`部分で候補写真の送信を行う.
> > > 
> > > 
> > > 変更承知しました。 `if timeout_flag:`部分で候補写真の送信を行う.の部分って、raiseすれば直接exceptに行って送信するではだめなんでしょうか？
> > > > あと、写真間の待機時間をそれぞれで保持している理由はありますか？個人的に全部同じ時間でいいのではないかと思うのですが、別々に設定したほうがいい理由があったら回答お願いします。
> > > 
> > > 
> > > 単純に各区間における写真間の待機時間は異なるからと言うのもあるのですが、固定した場合を考えると、 もし例えば、どの区間においても待機時間を15秒に固定して、区間1で画像を取得するまで10秒、区間2で5秒かかるとした場合、区間1でコースアウトしたと判定するまでに少なくとも5秒以上、区間2の場合は少なくとも10秒以上かかります。この判定時間が長いほど、コースアウトしてから場外に出てしまったり、相手コースの方に侵入してしまった場合に、画像を送信できない可能性が高まるので、個別に保持した方が良いと思っています。 でも、よく考えたら、どの区間も同じくらいの待機時間なので、同じ時間でもいいのかなと思いました。
> > 
> > 
> > raiseで終了したら、処理が終了してしまうよね。可能性として低いのだが、例えばBの画像を受信する前にタイムオーバーしてraiseによる送信をしたらBはあきらめることになるよね。タイムオーバーはあくまでタイムアウトの推測であって絶対ではないのでAを送ったとしてもBの画像を探し続けるべきだと思う。どうせコースアウトしたら人が止めるのだから、プログラム的に終了するようにする必要はないと思う。
> > 時間については検証を行うのであれば的確な時間を検証してもいいけど、あまり時間ないよね。仮に別々にしたいってなっても制限時間を配列として保持するか、一つの値として保持するかの違いで済む(列挙体をやめた場合)から分けたいと思ったときに複数設定するように変更すればいいと思う。
> 
> なるほどですね、了解です。 まとめると、修正点は
> 
> * raiseを消して、`if timeout_flag`:部分で候補写真の送信を行う.
> * 列挙子を消して、待機時間は一つの値として保持する
> 
> ということですね。 気になる点として、ミニフィグBの写真は撮れていて、ミニフィグAのベストショットが撮れていない場合は、候補写真を送ってしまってもいいのでしょうか？もし、ミニフィグB撮影以降でコースアウトし候補写真を送った後に、ミニフィグAのベストショットが奇跡的に取れたとしても、もう写真は送信できませんよね？

候補画像を送っていいよ。
となると、きれいに書く場合は、Fig_Bを送ったときに、以下のような条件式を足すべきだね。
```
if self.successful_send_candidate or self.successful_send_best_shot:
    break
```

あと、タイムアウトでFig_Aを送った際にFig_Bを送っているかのチェックをしてforを続けるかの処理も入れるのがベストかな

2023-11-09 15:37 UTC, kawanoichi commented on src/robo_snap.py
> +            start_time = 0.0  # 次の画像の受信開始前のタイムスタンプ
start_timeはfor文の中に入れないとリセットされない

2023-11-09 15:51 UTC, kawanoichi commented on src/robo_snap.py
> +                    continue
```suggestion
                # 配置エリアBの画像を取得した時の処理
                if img_name == self.fig_img_B:
                    self.fig_B_img_path = img_path
                    # 配置エリアBの画像は検出せずにアップロード
                    if OfficialInterface.upload_snap(self.fig_B_img_path):
                        self.successful_send_fig_B = True
                        if self.successful_send_best_shot or self.successful_send_candidate:
                            break
                    continue
                elif self.successful_send_best_shot or self.successful_send_candidate:
                    continue
                
                # コースアウトしているならば、候補写真を送信し、次の画像を探し続ける
                if timeout_flag:
                    if self.candidate_img_path is not None:
                        if OfficialInterface.upload_snap(self.candidate_img_path):
                            self.successful_send_candidate = True
                            if self.successful_send_fig_B:
                                break
                    timeout_flag = False
                    continue

```
209行目らへんからの提案なんだが、self.successful_send_best_shot = True は変数の意味と違ってくるので変えるべきかな。

2023-11-09 15:52 UTC, kawanoichi commented on src/robo_snap.py
> +            """タイムアップやエラー、コースアウトなどで終了した際の送信試み."""
```suggestion
            """エラー発生時の送信試み."""

```

2023-11-09 16:01 UTC, kawanoichi requested changes
あと、for文ではなくwhile使うのが適切かもね。

2023-11-10 04:23 UTC, aridome222 commented
> 都合よく終わらせることができるかもしれないが変数の意味は大事にしてほしいな。

了解です。以後気を付けます。

2023-11-10 04:25 UTC, aridome222 commented on src/robo_snap.py
> +            start_time = 0.0  # 次の画像の受信開始前のタイムスタンプ
下記で、開始時刻は初期化されると思ったのですが、入れた方がいいんですっけ？
```
# FigA_4でなければ、計測を開始する.
if img_name != "FigA_4.png":
    start_time = time.time()
break
```

2023-11-10 06:15 UTC, miyashita64 approved these changes
LGTM(Change Request撤回用)

2023-11-10 07:18 UTC, kawanoichi approved these changes
![213169](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/assets/96767490/0649cef2-e8c4-440f-9b7d-0bed7b9cda2a)

2023-11-11 05:56 UTC, bizyutyu commented
LGTM!

2023-11-11 09:36 UTC, bizyutyu approved these changes

2023-11-11 09:36 UTC, Negimarge approved these changes
LGTM

2023-11-11 09:38 UTC, merged