close #8 ロボットのサーバに定期的にリクエストを送る
KatLab-MiyazakiUniv/etrobocon2023-camera-system pull request #9
Opened 2023-06-30 20:45 UTC by aridome222

## チェックリスト

- [ ] format(autopep8) している
- [ ] コーディング規約(pep8)に準じている
- [ ] チケットの完了条件を満たしている

## 変更点
etrobocon2023-camera-system/src下において
- camera_system.pyを更新
- client.pyを追加

## 動作テスト
1. etrobocon2023/serverで、`$ python3 flask_server.py`をコマンドで打ち、サーバを起動させる。
2. etrobocon2023-camera-systemで、`$ make run`を打つ
3. カメラシステム側のコマンドライン上で、notReadyが定期的に出力される
4. `$ curl -X POST -H "Content-Type: text/plain" -d **'～'** http://127.0.0.1:8000/robot_info/state`で、**'～'**の部分を'wait'や'start'、'lap'にすれば、ロボットの状況を変えられる。
5.  **'～'**の部分を'finish'にすれば、サーバへの定期的なリクエストの送信を終了する。

2023-07-01 09:42 UTC, kawanoichi commented on src/camera_system.py
>          pass
```suggestion
        # キャリブレーション後に走行体状況監視モジュールを実行する
        client()
```
ここがいいかな

2023-07-01 09:43 UTC, kawanoichi commented on src/client.py
> +def Client():
```suggestion
def client():
```
関数名は小文字でいいかな

2023-07-01 09:55 UTC, kawanoichi commented on src/client.py
> +        # レスポンスが"notReady"の時
```suggestion
        # # レスポンスが"finish"になった時、終了する。
        if response_text == "finish":
            print(response_text)
            break
        else:
             print(response_text)
```
わざわざ分ける必要ないかな？

2023-07-02 08:28 UTC, bizyutyu approved these changes
確認した感じ、間違いはないように感じます。
![LGTM](https://images.lgtmgen.org/bd85aae4-5489-40d1-a1ae-c8cfde03ea40)

2023-07-02 17:16 UTC, kawanoichi approved these changes
![122267](https://github.com/KatLab-MiyazakiUniv/etrobocon2023-camera-system/assets/96767490/f069afe6-d1fd-4c83-a991-8848fbfc7dab)

2023-07-02 18:58 UTC, miyashita64 requested changes
レビュー遅くなってごめん。見逃してた。
処理の場所だけ変更してほしいです。

2023-07-02 18:58 UTC, miyashita64 commented on src/client.py
> +    def client(self):
Clientに色々させすぎだと思う。
ロボットの状態を取得するだけの`get_robot_state()`とかにして、camera_system.py側で繰り返す方が、他の処理と合わせやすいと思う。
```suggestion
    def get_robot_state(self):
```

2023-07-02 18:58 UTC, miyashita64 commented on src/client.py
> +            # 指定したurlにGETリクエストを投げてレスポンスを受け取る
```suggestion
```

2023-07-02 18:58 UTC, miyashita64 commented on src/client.py
> +            time.sleep(2)
```suggestion
            return response_text
```

2023-07-02 18:58 UTC, miyashita64 commented on src/camera_system.py
> +        client = Client()
今後どうなるかわからんけど、できれば実行時引数で渡したいからできるだけ上のクラスで設定したい
```suggestion
        server_ip = "192.168.11.17:8000"
        client = Client(server_ip)
```

2023-07-02 18:58 UTC, miyashita64 commented on src/client.py
> +
```suggestion
        def __init__(self, server_ip):
            self.server_ip = server_ip
```

2023-07-02 18:58 UTC, miyashita64 commented on src/client.py
> +        url = 'http://192.168.11.17:8000/robot_info/state'
```suggestion
        url = f"http://{self.server_ip}/robot_info/state"
```

2023-07-03 04:17 UTC, KakinokiKanta requested changes
細かいとこ1箇所だけ

2023-07-03 04:17 UTC, KakinokiKanta commented on src/camera_system.py
> +        # sever_ipは、et2023@katlabなら192.168.11.16、et2023@katlab2なら192.168.11.17
```suggestion
        # sever_ipは、走行体1なら192.168.11.16、走行体2なら192.168.11.17
```
この方が適切かな

2023-07-03 14:43 UTC, miyashita64 requested changes
テストがよくわからないです。教えてほしい。

2023-07-03 14:43 UTC, miyashita64 commented on tests/test_client.py
> +def test_client(mocker):
camera_systemの方では、Test_camera_systemがクラスとして書かれてるけどこっちはしなくていいの？

2023-07-03 14:43 UTC, miyashita64 commented on tests/test_camera_system.py
> +        cs = CameraSystem()
テストの意図がわからないです。
テストコード中のコメントとできれば参考文献載せてほしいです。

2023-07-04 06:21 UTC, kawanoichi commented on tests/test_camera_system.py
> +        cs = CameraSystem()
@miyashita64 処理を変えたのでもう一度レビューをよろしく

2023-07-04 14:23 UTC, miyashita64 approved these changes
![LGTM](https://image.lgtmoon.dev/174788)

2023-07-06 11:15 UTC, KakinokiKanta approved these changes
LGTM
![LGTM](https://image.lgtmoon.dev/214484)

2023-07-06 11:15 UTC, merged